import "bootstrap/dist/css/bootstrap.min.css";

const Head = (): JSX.Element => {
  return (
    <head>
      <title>CBook</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </head>
  );
};

export default Head;
